name: Auto Merge Rules

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Merge Script
        run: npm start

      - name: Commit & Push
        run: |
          git config user.name "Github-Actions[Bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add rules/apple.list
          git commit -m "Auto update rules on $(date -u +"%Y-%m-%d %H:%M:%S")" || echo "No changes"
          git push
